/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;
import service.SinhVienService;

/**
 *
 * @author admin
 */
public class SinhVienView extends javax.swing.JFrame {

    /**
     * Creates new form SinhVienView
     */
    SinhVienService sinhVienService = new SinhVienService();

    private int index = -1;

    DefaultTableModel defaultTableModel;

    public SinhVienView() throws SQLException {
        initComponents();

        defaultTableModel = (DefaultTableModel) tblSinhVien.getModel();
            
        
        String[] headertable = {
            "Id",
            "Mã SV",
            "Tên SV",
            "Điểm",
            "Ngành",
            "Gioi Tinh"
        };

        defaultTableModel.setColumnIdentifiers(headertable);

        defaultTableModel.setRowCount(0);

        cboNganh.removeAllItems();
        cboNganh.addItem("PTPM");
        cboNganh.addItem("UDPM");
        cboNganh.addItem("XLDL");
         cboNganh.addItem("WEB");
        // ĐẨY DỮ LIỆU Từ bảng trong sql lên form

        // Đổ dữ liệu từ bảng trong sql ra table
        this.fillTable(sinhVienService.getAllSinhViens());

    }

    private void fillTable(List<SinhVien> list) {
       defaultTableModel.setRowCount(0);
        for (SinhVien sv : list) {

            defaultTableModel.addRow(sv.toDataRow());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txMaSv = new javax.swing.JTextField();
        txtDiemTB = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        cboNganh = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        rdKxd = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiemTheoTen = new javax.swing.JButton();
        btnSapXepTheoDiem = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDiemTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemTBActionPerformed(evt);
            }
        });

        cboNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("ma Sv");

        jLabel2.setText("Ho Tên");

        jLabel3.setText("Nganh");

        jLabel4.setText("DiemTB");

        buttonGroup1.add(rdNam);
        rdNam.setText("Nam");
        rdNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdNamMouseClicked(evt);
            }
        });
        rdNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdNu);
        rdNu.setText("Nữ");
        rdNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNuActionPerformed(evt);
            }
        });

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSinhVien);

        buttonGroup1.add(rdKxd);
        rdKxd.setText("KXD");
        rdKxd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdKxdMouseClicked(evt);
            }
        });
        rdKxd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdKxdActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");

        btnXoa.setText("Xoa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnTimKiemTheoTen.setText("Tim kiếm theo tên");
        btnTimKiemTheoTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemTheoTenMouseClicked(evt);
            }
        });

        btnSapXepTheoDiem.setText("Sắp xếp theo điểm");
        btnSapXepTheoDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSapXepTheoDiemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdNam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdNu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdKxd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(47, 47, 47)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(46, 46, 46)
                                .addComponent(btnTimKiemTheoTen)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btnSapXepTheoDiem)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdNam)
                    .addComponent(rdNu)
                    .addComponent(rdKxd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnTimKiemTheoTen))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnSapXepTheoDiem)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiemTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemTBActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // Bước 1. Lấy đối tượng sinh viên mới
       SinhVien sinhVien = readForm();
       int kq = sinhVienService.insertSinhVien(sinhVien);
       if (kq > 0) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
           try {
               fillTable(sinhVienService.getAllSinhViens());
           } catch (Exception ex) {
               Logger.getLogger(SinhVienView.class.getName()).log(Level.SEVERE, null, ex);
           }
        }else {
           JOptionPane.showConfirmDialog(this, "Thêm thành công");
       }
        
        
        

    }//GEN-LAST:event_btnThemActionPerformed

    SinhVien readForm() {  
        String ma,ten,nganh;
        double diem;
        int gioiTinh;
        
        ma = txMaSv.getText().trim();
        ten = txtHoTen.getText().trim();
        nganh = cboNganh.getSelectedItem().toString();
        diem = Double.parseDouble(txtDiemTB.getText());
        
        if (rdNam.isSelected()) {
            gioiTinh = 1;
        }else if (rdNu.isSelected()) {
            gioiTinh = 0;
        }else {
            gioiTinh = 2;
        }
        
        return new SinhVien(ma, ten, diem, nganh, gioiTinh);
        
    }
    
    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked

        int row = tblSinhVien.getSelectedRow();
        
        index = row;

//        System.out.println(row);

        String ma = defaultTableModel.getValueAt(row, 1).toString();
        String ten = defaultTableModel.getValueAt(row, 2).toString();
        String diem = defaultTableModel.getValueAt(row, 3).toString();
        String nganh = defaultTableModel.getValueAt(row, 4).toString();
        String gt = defaultTableModel.getValueAt(row, 5).toString();
        
        

        txMaSv.setText(ma);
        txtHoTen.setText(ten);
        txtDiemTB.setText(diem);
        cboNganh.setSelectedItem(nganh);
        
        if (gt.equalsIgnoreCase("Nam")) {
            rdNam.setSelected(true);
        }else if (gt.equalsIgnoreCase("Nữ")) {
            rdNu.setSelected(true);
        }else {
            rdKxd.setSelected(true);
        }
        
//        txMaSv.setText();
//        txtHoTen.setText();
//        txtDiemTB.setText(txtSV);

    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void rdKxdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdKxdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdKxdActionPerformed

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa");
            return;
        }
        
        int row = tblSinhVien.getSelectedRow();

//        System.out.println(row);

        String ma = defaultTableModel.getValueAt(row, 1).toString();
        
        int kq = sinhVienService.delete(ma);
        
        if (kq > 0) {
            JOptionPane.showMessageDialog(this, "Xóa thành công ");
            this.fillTable(sinhVienService.getAllSinhViens());
        }else {
             JOptionPane.showMessageDialog(this, "Xóa không thành công ");
        }
       
        
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnTimKiemTheoTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemTheoTenMouseClicked
       
        String ten =  JOptionPane.showInputDialog(this, "Vui lòng nhập tên cần tìm");
        
       
        List<SinhVien> kq = sinhVienService.findSinhVienByTen(ten);
        if (kq.size() == 0) {
            JOptionPane.showMessageDialog(this, "Không tìm thây kết quả nào");
            fillTable(sinhVienService.getAllSinhViens());
        } else {
            JOptionPane.showMessageDialog(this, "Tìm được "+kq.size() + " sinh viên trùng khớp");
            fillTable(kq);
        }
        
        
    }//GEN-LAST:event_btnTimKiemTheoTenMouseClicked

    private void rdNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdNamMouseClicked
            
    }//GEN-LAST:event_rdNamMouseClicked

    private void rdNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNamActionPerformed
           List<SinhVien> sinhViens = sinhVienService.findSinhVienByGioiTinh(1);
           fillTable(sinhViens);
    }//GEN-LAST:event_rdNamActionPerformed

    private void rdNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNuActionPerformed
        List<SinhVien> sinhViens = sinhVienService.findSinhVienByGioiTinh(0);
         fillTable(sinhViens);
    }//GEN-LAST:event_rdNuActionPerformed

    private void rdKxdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdKxdMouseClicked
         List<SinhVien> sinhViens = sinhVienService.findSinhVienByGioiTinh(3);
           fillTable(sinhViens);
    }//GEN-LAST:event_rdKxdMouseClicked
    boolean a = false;
    private void btnSapXepTheoDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSapXepTheoDiemMouseClicked
        
        if (a == true) {
            a = !a;
        }else {
            a = true;
        }
        
        System.out.println(a);
            List<SinhVien> sinhViens = sinhVienService.getAllSinhViens();
        if ( a == true) {
         
         sinhViens.sort((p1, p2) -> { 
            return Double.compare(p2.getDiemTrungBinh(), p1.getDiemTrungBinh());
        });
        }else {
         sinhViens.sort((p1, p2) -> { 
            return Double.compare(p1.getDiemTrungBinh(), p2.getDiemTrungBinh());
        });
        }
         
         fillTable(sinhViens);
    }//GEN-LAST:event_btnSapXepTheoDiemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SinhVienView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SinhVienView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSapXepTheoDiem;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiemTheoTen;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboNganh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdKxd;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txMaSv;
    private javax.swing.JTextField txtDiemTB;
    private javax.swing.JTextField txtHoTen;
    // End of variables declaration//GEN-END:variables
}
